site_name: OSCP Documentation
site_url: https://docs.oscp.com
theme:
  name: material
  language: en
  logo: assets/images/oscp-emblem-white.svg
  favicon: assets/images/oscp-profil-primary.svg
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
copyright: "Copyright &copy; 2026, OSCPS Motion Sensing Inc. All rights reserved."
extra:
    generator: true
    homepage: https://www.oscp.com
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/one-silicon-chip-photonics/
          name: OSCP on LinkedIn
        - icon: fontawesome/brands/github
          link: https://github.com/OSCPS
          name: OSCP on GitHub
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/@oscpsmotionsensinginc.4037
          name: OSCP on YouTube
        - icon: fontawesome/brands/x-twitter
          link: https://x.com/onesiliconchip
          name: OSCP on X (formerly Twitter)
        - icon: fontawesome/brands/facebook
          link: https://www.facebook.com/profile.php?id=100042245063717
          name: OSCP on Facebook